name: Configure sway
steps:
  - !Link
    from: "config"
    to: "~/.config/sway/config"
  - !Link
    from: "conf.d"
    to: "~/.config/sway/conf.d"
    symbolic: true
  - !Copy
    from: "wallpaper.jpg"
    to: "~/.config/sway/wallpaper.jpg"
    recursive: false
  - !Copy
    from: "input.conf"
    to: "~/.config/sway/input.conf"
    recursive: false
  - !Copy
    from: "output.conf"
    to: "~/.config/sway/output.conf"
    recursive: false

