stages:
  - name: Configure kitty
    steps:
      - !Link
        from: "kitty"
        to: "~/.config/kitty"
        symbolic: true

  - name: Configure mako
    steps:
      - !Link
        from: "mako"
        to: "~/.config/mako"
        symbolic: true

  - from_file: sway/.install.yml

  - name: Configure swaylock
    steps:
      - !Link
        from: "swaylock"
        to: "~/.config/swaylock"
        symbolic: true

  - from_file: vim/.install.yml

  - name: Configure waybar
    steps:
      - !Link
        from: "waybar"
        to: "~/.config/waybar"
        symbolic: true

  - name: Configure wofi
    steps:
      - !Link
        from: "wofi"
        to: "~/.config/wofi"
        symbolic: true

  - from_file: zsh/.install.yml
