name: Configure sway
steps:
  - !Link
    from: "hyprland.conf"
    to: "~/.config/hypr/hyprland.conf"
    recursive: false
  - !Link
    from: "binds.conf"
    to: "~/.config/hypr/binds.conf"
    recursive: false
  - !Link
    from: "hyprpaper.conf"
    to: "~/.config/hypr/hyprpaper.conf"
    recursive: false
  - !Link
    from: "input.conf"
    to: "~/.config/hypr/input.conf"
    recursive: false
  - !Link
    from: "monitors.conf"
    to: "~/.config/hypr/monitors.conf"
    recursive: false
  - !Link
    from: "rules.conf"
    to: "~/.config/hypr/rules.conf"
    recursive: false
  - !Link
    from: "settings.conf"
    to: "~/.config/hypr/settings.conf"
    recursive: false
  - !Link
    from: "startup.conf"
    to: "~/.config/hypr/startup.conf"
    recursive: false
  - !Link
    from: "wallpaper.jpg"
    to: "~/.config/hypr/wallpaper.jpg"
    recursive: false
