timeout = 1000
max = 100
anchor = top center

border_color = 434e59
bar_color = d9d8d8
background_color = 22282e
overflow_border_color = 424e59
overflow_bar_color = ee2e34
overflow_background_color = d9d8d8

height = 25
width = 250

bar_padding = 0
border_size = 3
border_offset = 0

# [output.laptop]
# Name = eDP-1

[style.muted]
background_color = 032cfc
